version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "pip"
    directory: "/backend/app"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "uvicorn"
        versions: ["0.30.0"]
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
